// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Script = 1,
  Cell = 2,
  Comment = 3,
  Statement = 4,
  Base_numbers = 5,
  Base_Operator = 6,
  Identifier = 7,
  Keyword = 8,
  Assignment = 9,
  Call = 10,
  FunIdentifier = 11,
  StartRBrack = 12,
  EndRBrack = 13,
  StartABrack = 14,
  EndABrack = 15
