// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,per:54, to:54, let:54, fn:54, where:54, and:54, dimension:54, unit:54, use:54, long:54, short:54, both:54, none:54, print:54, assert:54, assert_eq:54, type:54, if:54, then:54, else:54, true:54, false:54}
export const parser = LRParser.deserialize({
  version: 14,
  states: "&rOVQPOOOqQPO'#CmO!_QPO'#C^OOQO'#Cd'#CdO!fQPO'#CgO#WQQO'#CzOOQO'#Co'#CoO#zQPO'#C`O$XQPO'#CnOvQPO'#C^O$^QPO'#ClQVQPOOO$cQPO'#CfOOQO,59X,59XOOQO-E6k-E6kO$hQPO,58xOOQO'#Cp'#CpO$oQQO'#C{O$zQQO'#CrO$rQQO'#C{O$rQQO'#C{O%YQQO,59fOOQO-E6m-E6mOOQO,59Y,59YOOQO-E6l-E6lOOQO,59W,59WOOQO-E6j-E6jO%_QPO,59QOOQO-E6n-E6nO%lQQO,59gO%tQQO,59^OOQO,59^,59^OOQO-E6p-E6pOOQO1G/Q1G/QO&PQPO'#CxO&[QPO'#CqO&SQPO'#CxO&SQPO'#CxO&iQPO1G.lO&nQPO,59dO&vQPO,59]OOQO,59],59]OOQO-E6o-E6oOOQO7+$W7+$W",
  stateData: "'W~OiOS~ORPOTUOUUOVSOXUO^TOkROjQP~Oj]O~OTUOUUOVSOXUO^TOkROjQX~ORPO~PvOTcXUcXVcXXcX[ZX^cXjcXkcX]cXmcX~OVdOj`OmbO_oP~OTUOUUOVSOXUO^TOkRO~OjSX]SXmSX~P#fOjgO~OjiO~O[kO~OjQa~P#fOj`OmbO_oX~OVoOj`O_fXmfX~O_qO~Oj`OmsO]lP~P#fOmbO_oa~Oj`O_famfa~Oj`OmsO]lX~Oj`O]eXmeX~P#fO]{O~OmsO]la~Oj`O]eamea~OVU^U~",
  goto: "$^pPPqPuPPP!SP!S!^PPPP!h!n!u#Q#^#p#{PPPPP$WP!S$ZTYOZYWOQXZ_QukRysaUOQVXZ_ksa[OQVXZ_ksQZORjZSQOZR^QSXOZQ_QThX_^VOQXZ_ksRfVQaTWlanrxQnbQrkRxsQtkSwruTztwQcTSmadTpcmRvkReT",
  nodeNames: "⚠ Script Cell Comment Statement Base_numbers Base_Operator Identifier Keyword Assignment Call FunIdentifier StartRBrack EndRBrack StartABrack EndABrack",
  maxTerm: 31,
  nodeProps: [
    ["group", 4,"statement"],
    ["closedBy", 12,"EndRBrack",14,"EndABrack"],
    ["openedBy", 13,"StartRBrack",15,"StartABrack"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 7,
  tokenData: ".b~R!sXY&`YZ&qZ[&`pq&`st&vxy'_yz'dz{'i{|'i|}'n}!O'i!O!P's!P!Q'i!Q!R(s!R![(k![!]'i!^!_*d!_!`*k!`!a*p!c!}*w#Q#R'i#T#o*w$f$g&`$x$y'i$y$z'i%o%p'i&a&b'i4w4x+S4x4y+S4y4z+S4z4{+S4{4|+S4|4}+S4}5O+S5O5P+S5P5Q+S5Q5R+S5R5S+S5S5T+S5T5U+S5U5V+S5V5W+S5W5X+S5X5Y+S5Z5[+S5[5]+S5]5^+S5^5_+S5_5`+S5`5a+S5a5b+S5i5j+S5j5k+S5k5l+S5l5m+S5m5n+S5n5o+S5o5p+S5p5q+S5q5r+S5r5s+S5s5t+S5t5u+S5u5v+S5v5w+S5w5x+S5x5y+S5y5z+S5z5{+S5{5|+S5|5}+S5}6O+S6O6P+S6P6Q+S6Q6R+S6R6S+S%#v%#w'i%(^%(_'i%(b%(c'i%(c%(d'i%Ef%Eg'i~&eSi~XY&`Z[&`pq&`$f$g&`~&vOj~~&{SR~OY&vZ;'S&v;'S;=`'X<%lO&v~'[P;=`<%l&v~'dO[~~'iO]~P'nOUP~'sOm~~'vP!Q!['y~(ORT~!Q!['y!g!h(X#X#Y(X~([R{|(e}!O(e!Q![(k~(hP!Q![(k~(pPT~!Q![(k~(xST~!Q![(k#U#V)U#c#d)j#l#m)x~)XQ!Q!R)_!R!S)_~)dQT~!Q!R)_!R!S)_~)mP!Q!Y)p~)uPT~!Q!Y)p~){R!Q![*U!c!i*U#T#Z*U~*ZRT~!Q![*U!c!i*U#T#Z*U~*kOUP^~~*pOX~R*wO_QUP~*|QV~!Q![*w!c#o*w~+X!RV~4w4x+S4x4y+S4y4z+S4z4{+S4{4|+S4|4}+S4}5O+S5O5P+S5P5Q+S5Q5R+S5R5S+S5S5T+S5T5U+S5U5V+S5V5W+S5W5X+S5X5Y+S5Z5[+S5[5]+S5]5^+S5^5_+S5_5`+S5`5a+S5a5b+S5i5j+S5j5k+S5k5l+S5l5m+S5m5n+S5n5o+S5o5p+S5p5q+S5q5r+S5r5s+S5s5t+S5t5u+S5u5v+S5v5w+S5w5x+S5x5y+S5y5z+S5z5{+S5{5|+S5|5}+S5}6O+S6O6P+S6P6Q+S6Q6R+S6R6S+S",
  tokenizers: [0, 1],
  topRules: {"Script":[0,1]},
  specialized: [{term: 7, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 279
})
