name: Release Obsidian plugin

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Install
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

            - name: build wasm
              run: |
                  cd kernels/numbat-kernel && wasm-pack build --target=web --release
              env:
                  RUSTFLAGS: '--cfg getrandom_backend="wasm_js"'

            - name: Build plugin
              run: |
                  pnpm install
                  pnpm run build

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tag="${GITHUB_REF#refs/tags/}"

                  gh release create "$tag" \
                    --title="$tag" \
                    --draft \
                    dist/main.js dist/manifest.json dist/styles.css
